# NumPy Basics

advantage(?)

In [1]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr *2
    
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 31.3 ms
Wall time: 1 s


In [1]:
import numpy as np

data = np.random.randn(2, 3)
data

array([[-0.94527239,  0.01570697,  1.36871484],
       [-0.85969826,  0.67264113, -1.21681157]])

In [2]:
data * 10

array([[ -9.45272394,   0.15706966,  13.68714841],
       [ -8.5969826 ,   6.72641126, -12.16811567]])

In [3]:
data + data

array([[-1.89054479,  0.03141393,  2.73742968],
       [-1.71939652,  1.34528225, -2.43362313]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

## creating ndarrays

In [7]:
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [11]:
arr2.dtype

dtype('int32')

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [23]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int32')

In [24]:
arr = np.array([1, 2, 3, 4, 5])

arr.dtype

dtype('int32')

In [25]:
float_arr = arr.astype(np.float64)

float_arr.dtype

dtype('float64')

In [26]:
arr = np.array([[1.0, 2., 3], [4., 5., 6.]])

In [27]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [29]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [31]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [32]:
arr == arr

array([[ True,  True,  True],
       [ True,  True,  True]])

In [33]:
arr != arr

array([[False, False, False],
       [False, False, False]])

In [34]:
arr > 1

array([[False,  True,  True],
       [ True,  True,  True]])

In [35]:
arr > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [36]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [37]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr[5:8] = 12

arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])